/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gmail.volodymyrdotsenko.tls;

import java.util.List;

public class App {

    public static void main(String[] args) throws InterruptedException {
        var service = new Service();
        new Thread(new RequestHandler(service, List.of(new Request("user1", "pass1")))).start();
        new Thread(new RequestHandler(service, List.of(new Request("user2", "pass2")))).start();

        Thread.sleep(1000);

        new Thread(new RequestHandler(
                service,
                List.of(new Request("user1", "pass12"),
                        new Request("user1", "pass1"),
                        new Request("user1", "pass1"))))
                .start();
        new Thread(new RequestHandler(service, List.of(new Request("user1", "pass2")))).start();
    }
}
